// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuehipsrzsyqqmmbeens.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1ZWhpcHNyenN5cXFtbWJlZW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTYzNTMsImV4cCI6MjA2NDYzMjM1M30.DOMF2ccieSyY8ZNJbR_yLE2JhPXvQuPeDJniLNMUhKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);